### ISSUE TITLE
A Bug in `deal_post_data`

### ISSUE THREAD

**Issue by YG-FLUSH** [Rochester-NRT/AlphaGo#34]
When I am trying to run `python goServer.py` in the `interface/server/` directory and trying to upload a `.sgf` file, the url change from`/go.html` to `/go.html?file=Can't create file to write, do you have permission to write?`, and nothing else have happened.

This error shows that it must be something wrong with the file permission. Please Solve it，thanks！

**Comment by wrongu** [comment]
`goServer.py` is a work in progress - it doesn't do anything very exciting yet. We'll make sure to put together clear specs for it tomorrow.
