### ISSUE TITLE
Library choice

### ISSUE THREAD

**Issue by Nefeste** [Rochester-NRT/AlphaGo#37]
Why Theano+keras+numpy, and not Caffe? Seems like Caffe have a greater speed and allows to use GPUs, and more widely used as compared to neon/Nervanasys

**Comment by danielrich** [comment]
theano lets you use GPUs too. Keras sits on top of theano and provides a much nicer more abstract interface than caffe. I wasn't involved in the decision here but we do use theano and keras at work.

**Comment by wrongu** [comment]
Yes - what @danielrich said. We were also thinking of this project more as a reference implementation than a fully optimized 9-dan player (though that would be good as well!). Keras also stood out to us given that our group is comprised of people most comfortable with python

**Comment by ttrine** [comment]
Hi! We're excited to have fresh interest in the project. If I could just add to wrongu's comment, we are definitely open to implementations in more than just Keras. We decided to start with Keras/Python so we can build out the project as quickly as possible within our small team.
