### ISSUE TITLE
how to build AlphaGo to play chess?

### ISSUE THREAD

**Issue by the263** [Rochester-NRT/AlphaGo#39]
I have run the command "pip install -r requirements.txt" complete.

Now, after this, how can I play chess with AlphaGo??

**Comment by Nefeste** [comment]
@the263 AlphaGo is for Go (baduk, weiqi), not for chess. And it's still in the early development phase, there is no playing bot yet.

**Comment by the263** [comment]
It's google translation bad!!  I used it to translate playing... get the
"playing chess" result
So when can playing with AlphaGo. I am very interesting with it.
