### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by AbdielNie** [Rochester-NRT/AlphaGo#40]
I want to play chess with AlphaGo ,I have python 3.5,so how can I use it

**Comment by Nefeste** [comment]
@AbdielNie First of all, AlphaGo is for Go actually, not for chess. Secondly, it's recommended, that you have python 2.7. And finally, AlphaGo is still in the development stage, please be patient and come back soon.

**Comment by AbdielNie** [comment]
@Nefeste I just want to play with alphago,I am soooo boring that I want to have something to play with me.And I will try my best for this toy.
