### ISSUE TITLE
Other implementation

### ISSUE THREAD

**Issue by gogogeo** [Rochester-NRT/AlphaGo#50]
I am not sure if it can be used in this project - but please check, quite interesting and already working...
https://chrisc36.github.io/deep-go/

**Comment by wrongu** [comment]
AlphaGo certainly isn't the first AI to use convnets! The differences are primarily in what features they use and how they are trained. AlphaGo's success also has a lot to do with the value network/tree search.

So - in the future, we may come back to these other works for reference and/or inspiration for experimentation. For now, we'll stick to DeepMind's specifications.
