### ISSUE TITLE
Refactor SGF conversions?

### ISSUE THREAD

**Issue by wrongu** [Rochester-NRT/AlphaGo#51]
@ttrine and I never fully agreed on whether the `GameState` to/from SGF functionality would be part of the `GameState` class itself or reside in `game_converter`. Maybe the most reasonable thing to do would be to refactor the conversions entirely (i.e. some `state_to_sgf` and `sgf_to_state` in a separate file).

**Comment by wrongu** [comment]
Also note that the current SGF loading is incomplete, leading to some bugs. Looking at [this list](http://senseis.xmp.net/?SmartGameFormat) there are some necessary features for processing games that the current code doesn't do. Namely the following aren't currently handled:

- handicaps, properties 'AB' and 'AW'
- komi, property 'KM'
- check on the board size, property 'SZ'
- who starts, property 'PL'
    - or, we set `current_player` according to moves starting with `W` or `B`

**Comment by jtauber** [comment]
Shall I try to address this ticket using jtauber/sgf, per #53 ?

**Comment by Nefeste** [comment]
i have more SGF files, if you interested, please feel free to contact me michail.manylov at gmail dot com

**Comment by wrongu** [comment]
@jtauber go ahead! This one needs to be finished quickly since a few other tickets are waiting on it. I also feel comfortable enough with your `sgf` library to fix this issue, so I can do it later today if you can't get to it right away.

**Comment by jtauber** [comment]
I'm out for a while so go for it!

On Saturday, March 19, 2016, wrongu <notifications@github.com> wrote:

> @jtauber <https://github.com/jtauber> go ahead! This one needs to be
> finished quickly since a few other tickets are waiting on it. I also feel
> comfortable enough with your sgf library to fix this issue, so I can do
> it later today if you can't get to it right away.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Rochester-NRT/AlphaGo/issues/51#issuecomment-198750666>
>


-- 
James Tauber
http://jtauber.com/
@jtauber on Twitter

**Comment by linrio** [comment]
@wrongu When I run the **Feature conversion script**
# `python -m AlphaGo.preprocessing.game_converter -f all -o outfile/ -R -d tests/test_data/sgf/ -s SZ[19]  -v`
  
It returns error:
_using features ['board', 'ones', 'turns_since', 'liberties', 'capture_size', 'self_atari_size', 'liberties_after', 'sensibleness', 'zeros']
sgfs_to_hdf5 failed
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/lingfeng/alphago/AlphaGo-develop/AlphaGo/preprocessing/game_converter.py", line 218, in <module>
    run_game_converter()
  File "/home/lingfeng/alphago/AlphaGo-develop/AlphaGo/preprocessing/game_converter.py", line 214, in run_game_converter
    converter.sgfs_to_hdf5(files, args.outfile, bd_size=args.size, verbose=args.verbose)
  File "/home/lingfeng/alphago/AlphaGo-develop/AlphaGo/preprocessing/game_converter.py", line 133, in sgfs_to_hdf5
    raise e
TypeError: Can't convert element 2 (SZ[19]) to hsize_t
_
 May I ask how to check on the board size in the project?, I did`t find out from 'SZ'?
