### ISSUE TITLE
consider switching to jtauber/sgf for sgf library

### ISSUE THREAD

**Issue by jtauber** [Rochester-NRT/AlphaGo#53]
Just creating an issue here for discussion (close if it's a non-starter).

The code base currently has an old SGF parsing library that's LGPL and from 2000.

If you are at all interested in a pip installable, MIT-licensed SGF parsing library that will be actively maintained by someone already contributing to this repo, I'd be delight to make sure https://github.com/jtauber/sgf is up to the task.

**Comment by ttrine** [comment]
So Richard and I just discovered that the current SGF library doesn't handle handicaps appropriately. We think this is the nail in the coffin - let's use your library so that we can, as you say, actively maintain its functionality.
How should we proceed?

**Comment by jtauber** [comment]
I'm not completely happy with the current API (I wrote it in 2002 when I was fairly new to Python) so I'm going to do a bit of clean up but want to do that with your needs in mind. As well as any tweaks to the actual API (and data structure produced by the parser), let me know if it has any shortcomings via issues on https://github.com/jtauber/sgf

I'll likely start building out some unit tests shortly so if you hit any issues (besides API tweaks), let me know the particular SGF that's causing problems and I'll make sure it's supported and there are unit tests that cover it.

**Comment by jtauber** [comment]
I've made the API a lot more modern and written tests to achieve 100% test coverage.
