### ISSUE TITLE
This is interesting. Would you please develop what it is about ?

### ISSUE THREAD

**Issue by tomsihap** [Rochester-NRT/AlphaGo#55]
Hi,
I guess that this is an AlphaGo model which was coming with the Nature's publication about AlphaGo. This is fascinating, but would you explain a bit more what the repo is (if there were more than my guess) ?

**Comment by wrongu** [comment]
We are not affiliated with DeepMind. This project is a work-in-progress to replicate their results, so it will stay as true to their AlphaGo as possible.

**Comment by LetterRip** [comment]
Read the readme :)  This is a reimplementation/replication of of the AlphaGo model based on the Nature publication.
