### ISSUE TITLE
How to run the AlphaGo project on our computer?How can I import sgf?

### ISSUE THREAD

**Issue by linrio** [Rochester-NRT/AlphaGo#78]
My computer is centOS 7 with linux x86_64, and it has not GPU.
I want to know how to run the AlphaGo project?
when I #`python -m AlphaGo.preprocessing.game_converter --help`
It shows error:
_[root@localhost AlphaGo-develop]# python -m AlphaGo.preprocessing.game_converter --help
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/lingfeng/alphago/AlphaGo-develop/AlphaGo/preprocessing/game_converter.py", line 4, in <module>
    from AlphaGo.util import sgf_iter_states
  File "AlphaGo/util.py", line 1, in <module>
    import sgf
ImportError: No module named sgf
_

**ImportError: No module named sgf**

How can I import sgf?

**Comment by wrongu** [comment]
you first need to install the dependencies; `pip install -r requirements.txt`

**Comment by linrio** [comment]
@wrongu Thanks for your guide. Now I run the unittests and Benchmarks:
_[root@lf AlphaGo-develop]# python -m unittest discover
Using Theano backend.
.....................Epoch 1/1
960/960 [==============================] - 4s - loss: 0.3501 - val_loss: 0.3441
.
----------------------------------------------------------------------
Ran 22 tests in 51.106s

OK
[root@lf AlphaGo-develop]# python -m tests.test_policy
Using Theano backend.
...
----------------------------------------------------------------------
Ran 3 tests in 4.351s

OK
[root@lf AlphaGo-develop]# python -m tests.test_policy TestCNNPolicy.test_save_load
Using Theano backend.
.
----------------------------------------------------------------------
Ran 1 test in 2.236s

OK
[root@lf AlphaGo-develop]# python -m benchmarks.preprocessing_benchmark
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/lingfeng/alphago/AlphaGo-develop/benchmarks/preprocessing_benchmark.py", line 7, in <module>
    gc = game_converter()
**TypeError: __init__() takes exactly 2 arguments (1 given)**_

It seems some thing wrong in Benchmarks.What happen?
And how can I see the real board to play Go with computer?
