### ISSUE TITLE
How can I run Benchmarks?

### ISSUE THREAD

**Issue by linrio** [Rochester-NRT/AlphaGo#80]
After runing unittests, I try to run Benchmarks,
1, #` python -m benchmarks.preprocessing_benchmark`
2, The results are: 
_[root@lf AlphaGo-develop]# python -m benchmarks.preprocessing_benchmark
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/lingfeng/alphago/AlphaGo-develop/benchmarks/preprocessing_benchmark.py", line 7, in <module>
   gc = game_converter()
TypeError: __init__() takes exactly 2 arguments (1 given)
_

How can I solve this problem? And How can I receive` .prof `file ?

**Comment by linrio** [comment]
mistakes happen:
**  File "/home/lingfeng/alphago/AlphaGo-develop/benchmarks/preprocessing_benchmark.py", line 7, in <module>
    gc = game_converter()
TypeError: __init__() takes exactly 2 arguments (1 given)
**

**Comment by wrongu** [comment]
sorry about that - a recent update broke this benchmark. should be working now

**Comment by linrio** [comment]
I should download the new Download.zip? @wrongu

**Comment by wrongu** [comment]
Not sure what you mean by Download.zip - download the latest version of the code (or merge or re-clone it)

**Comment by linrio** [comment]
@wrongu I have update the code.
