### ISSUE TITLE
Python, multithreading and lock free MCTS...?

### ISSUE THREAD

**Issue by lake4790k** [Rochester-NRT/AlphaGo#94]
I understand you intend this to be a reference implementation, but I think for AlphaGo Python is just not appropriate.

The single machine version of AlphaGo is described as running on a machine with 48 cores and 8 gpus. The computation is a collective of parallel gpu neural net operations and cpu MCTSs. 8 cores are dedicated to controlling the 8 gpus, but that is only half of the story, the other half is the remaining 40 cores that are performing asynchronous MCTS (as in https://webdocs.cs.ualberta.ca/~mmueller/ps/enzenberger-mueller-acg12.pdf).

This lock free MCTS requires full control over the shared data structure to work properly and ensures almost linear performance scaling with the number of cores.

There is a serious issue with using Python for AlphaGo: not only its slow single threaded (because of being interpreted and not native), it can't do any real multithreading either because of the GIL, let alone fine grained shared memory access to implement such a lock free algorithm, and also coordinating gpu nn results with MCTS.

It's not that a python implementation wouldn't scale on a monster 48 cpu + 8 gpu system, it wouldn't scale on a basic 8 core computer, being basically single threaded.

Great effort, neural net training is fine done in python, but for later stages I would recommend using a language with real multithreading capabilities for this. Just my two cents, you can just close this issue.

**Comment by thouis** [comment]
Thanks for the advice.  Cython sidesteps all of this, if/when it becomes an actual issue.

**Comment by wrongu** [comment]
Thanks for the thorough comment! We have a few options:

1. Be OK with the slowness of this implementation (it is in part for reference, as you noted). We will still have all the neural nets trained in Python and loadable into other faster languages for search
2. Explore Python implementations without a GIL (do they work with theano and numpy?)
3. Make a fast C module as Thouis suggested
4. Make it multiprocessed

Useful: http://python-notes.curiousefficiency.org/en/latest/python3/multicore_python.html

**Comment by lake4790k** [comment]
Cool, cython shouldbe  powerful enough for an efficient implementation.
